import { Header } from "./components/Header";
import "../styles/tailwind.css";

export const metadata = {
  title: "Nexxjs World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-900 text-zinc-100">
        <Header />
        <div className="flex flex-col min-h-[calc(100vh-80px)] bg-zinc-800 px-20">
          {children}
        </div>
      </body>
    </html>
  );
}
